# Generated by Django 3.2.12 on 2022-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_cents', models.IntegerField(default=0)),
                ('settled_balance_cents', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('current', 'current'), ('delinquent', 'delinquent'), ('closed', 'closed')], default='current', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(default=0)),
                ('merchant_name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('posted', 'posted')], default='pending', max_length=32)),
                ('settled_amount_cents', models.IntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account')),
            ],
        ),
    ]
