# Generated by Django 3.2.12 on 2022-09-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220929_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('posted', 'posted')], default='pending', max_length=32),
        ),
    ]
